name: Deploy Next.js to Cloudflare Pages with Workers API

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "CLOUDFLARE_DATABASE_ID=${{ secrets.CLOUDFLARE_DATABASE_ID }}" >> $GITHUB_ENV

      - name: Build Next.js project
        run: npm run build && npm run export  # Ensures Next.js static export for Pages

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: connectnext
          branch: main
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: out  # Change from `.next` to `out` (static export output)

      - name: Deploy Cloudflare Worker API (Optional)
        run: npx wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
